export default [
  {
    id: "1",
    brand: "Castrol",
    name: "Castrol",
    liter: "1",
    price: "823р.",
    image: "images/oil2.png",
  },
  {
    id: "2",
    brand: "Mobil",
    name: "Mobil ULTRA",
    liter: "1",
    price: "953р.",
    image: "images/oil.png",
  },
  {
    id: "3",
    brand: "Ford",
    name: "Ford",
    liter: "1",
    price: "764р.",
    image: "images/oil2.png",
  },
  {
    id: "4",
    brand: "General Motors",
    name: "General Motors",
    liter: "1",
    price: "674р.",
    image: "images/oil.png",
  },
  {
    id: "5",
    brand: "Liqui Moly",
    name: "Liqui Moly",
    liter: "0.5",
    price: "674р",
    image: "images/oil2.png",
  },
  {
    id: "6",
    brand: "Nissan",
    name: "Nissan",
    liter: "1",
    price: "674р",
    image: "images/oil.png",
  },
 {
    id: "7",
    brand: "Total",
    name: "Total",
    liter: "1",
    price: "674р",
    image: "images/oil2.png",
  },
  {
    id: "8",
    brand: "Nissan",
    name: "Nissan",
    liter: "0.5",
    price: "56р",
    image: "images/oil.png",
  },
  {
    id: "9",
    brand: "Castrol",
    name: "Castrol",
    liter: "1",
    price: "823р",
    image: "images/oil2.png",
  },
  {
    id: "10",
    brand: "Mobil",
    name: "Mobil ULTRA",
    liter: "0.25",
    price: "953р",
    image: "images/oil.png",
  },
  {
    id: "11",
    brand: "Castrol",
    name: "Castrol",
    liter: "0.1",
    price: "823р",
    image: "images/oil2.png",
  },
  {
    id: "12",
    brand: "Mobil",
    name: "Mobil ULTRA",
    liter: "0.6",
    price: "953р",
    image: "images/oil.png",
  }  
]
